name: Deploy NGINX on VirtualBox VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install VirtualBox and Vagrant
        run: |
          sudo apt update
          sudo apt install -y virtualbox vagrant

      - name: Start VM with Vagrant
        run: |
          vagrant up
          
      - name: Validate NGINX Deployment
        run: |
          vagrant ssh -c "curl -I http://localhost"
