name: Deploy NGINX to VirtualBox VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH Access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 192.168.56.10 >> ~/.ssh/known_hosts

      - name: Install & Configure NGINX on VirtualBox VM
        run: |
          ssh vagrant@192.168.56.10 << 'EOF'
          sudo apt update -y
          sudo apt install -y nginx
          echo "<h1>Deployed via GitHub Actions!</h1>" | sudo tee /var/www/html/index.html
          sudo systemctl restart nginx
          EOF

      - name: Verify Deployment
        run: curl -I http://192.168.56.10
